from setuptools import find_packages, setup

setup(
    name="StockAnalyzer",
    version="0.2",
    description="stock analyzer",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    long_description_content_type="text/markdown",
    author="Ngoc Tram Ly",
    author_email="lyngoctram1709@gmail.com",
    license="MIT",
    classifiers=[
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent"
    ],
    install_requires=[
        "ansi2html==1.9.1",
        "bcrypt==4.1.2",
        "blinker==1.7.0",
        "certifi==2023.11.17",
        "cffi==1.16.0",
        "charset-normalizer==3.3.2",
        "click==8.1.7",
        "coverage==7.4.0",
        "cryptography==41.0.7",
        "dash==2.14.2",
        "dash-core-components==2.0.0",
        "dash-html-components==2.0.0",
        "dash-table==5.0.0",
        "decorator==5.1.1",
        "Deprecated==1.2.14",
        "fabric==3.2.2",
        "Flask==3.0.0",
        "idna==3.6",
        "importlib-metadata==7.0.1",
        "invoke==2.2.0",
        "itsdangerous==2.1.2",
        "Jinja2==3.1.2",
        "MarkupSafe==2.1.3",
        "nest-asyncio==1.5.8",
        "numpy==1.26.3",
        "packaging==23.2",
        "pandas==2.1.4",
        "pandas-schema==0.3.6",
        "paramiko==2.12.0",
        "plotly==5.18.0",
        "pycparser==2.21",
        "PyNaCl==1.5.0",
        "python-dateutil==2.8.2",
        "pytz==2023.3.post1",
        "requests==2.31.0",
        "retrying==1.3.4",
        "six==1.16.0",
        "tenacity==8.2.3",
        "typing_extensions==4.9.0",
        "tzdata==2023.4",
        "urllib3==2.1.0",
        "Werkzeug==3.0.1",
        "wrapt==1.16.0",
        "zipp==3.17.0",
    ],
    python_requires=">=3.10"
)
